# print('hello' 'world')
# print('hello','world')
# print('hello'+'world')
# print('hello ','world')
# print('hello ''world' )
# print(5//2)
# print(5/2)
# print(5*2)
# print(5+2)
# print(10>7>6)
# print(10%3)
# a=input("请输入用户名: ")
# print("欢迎：",a)            #中间为什么不能用空格隔开
# print('hello''world',sep='***')
# print('hello','world',sep='****')                   #，号间隔生效
# print('hello'+'world',sep='****')
# print('hello ''world',sep='****')
# print('hello','world',sep='****',end='--------')
# print('hello','world')                               #一行
_aaaa=('hello')
print(_aaaa)
bbb=('world')
print('hello','world')
#2xxx=('hello')              #不能以数字开头
#print(2xxx)
# qqqqqq=input("请输入数字： ")
# wwwwww=input("请输入数字： ")
# print(qqqqqq+wwwwww)
# qqqqqq=int(input("请输入数字： "))
# wwwwww=int(input("请输入数字： "))
# print(qqqqqq+wwwwww)
# print('hello','world')
# phine=input('请输入名称')
# print('收集型号'+dd)
print()


